"""empty message

Revision ID: 3334e6de4926
Revises: d55708694b98
Create Date: 2024-11-22 04:55:23.559739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3334e6de4926'
down_revision: Union[str, None] = 'd55708694b98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secrets', sa.Column('message', sa.String(), nullable=True))
    op.add_column('secrets', sa.Column('passphrase', sa.String(), nullable=True))
    op.add_column('secrets', sa.Column('secret_key', sa.String(), nullable=True))
    op.alter_column('secrets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_column('secrets', 'secret_password')
    op.drop_column('secrets', 'secret_message')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secrets', sa.Column('secret_message', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('secrets', sa.Column('secret_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('secrets', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('secrets', 'secret_key')
    op.drop_column('secrets', 'passphrase')
    op.drop_column('secrets', 'message')
    # ### end Alembic commands ###
